apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    name: deployment
  template:
    containers:
      - name: container
        image: registry/conatiner:latest
