version: "3"
services:
  # Server
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: devOpsTargil
    ports:
      - "3030:3030"
    env_file:
      - ./env/devOpsTargil.env
    environment:
      - APP_PORT
      - APP_NAME
    volumes:
      - .:/home/app
      - node_modules:/home/app/
    expose:
      - 3030
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
